
## 12. 예외 처리
> 프로그램을 실행했을 때 비정상적으로 종료하는 것을 오류(error)라고 생각할 수 있지만, 이것의 실체는 예외(exception)이다. <br>
> 이러한 예외를 처리하기위해 개발자들이 많은 코드를 작성하는데, 오류가 발생했을때 예외상황을 try / catch로 묶어두면 사용자에게 예외상황을 알리고 프로그램은 계속 실행한 상태로 남겨둘 수 있다.

- [배열 예외 처리](https://github.com/SeoDongWoo1216/StudyCSharp21/blob/main/chap12/chap12App/21_03_02_01_FirstexceptionApp/Program.cs)
- [예외 발생시키기](https://github.com/SeoDongWoo1216/StudyCSharp21/blob/main/chap12/chap12App/21_03_02_03_ExceptionThrowApp/Program.cs)
- [try ~ catch](https://github.com/SeoDongWoo1216/StudyCSharp21/blob/main/chap12/chap12App/21_03_02_02_TryCatchApp/Program.cs)
- [try ~ catch ~ finally](https://github.com/SeoDongWoo1216/StudyCSharp21/blob/main/chap12/chap12App/21_03_02_04_TryCatchFinallyApp/Program.cs)
